name: 'GitHub Actions BingPicApi'

on:
  push:
    branches: 
      -  master
  schedule:
    - cron: '0 8 * * *'

jobs:
  Bing-spider:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: bash ./main.sh
      - name: Commit files
        run: |
          time=$(date "+%Y%m%d")
          png=$time.png
          cd pic
          cp -f $png  ../everyday.png
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "ðŸ›° add a BingPic" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: Bing_Pic
